### ISSUE TITLE
Documentation at https://github.com/Nosto/wiki-docs/blob/Magento2/guides/managing-blocks.md has multiple errors

### ISSUE THREAD

**Issue by eCommerceGorilla** [supercid/wiki-docs#7]
The documentation at https://github.com/Nosto/wiki-docs/blob/Magento2/guides/managing-blocks.md has multiple errors. Including missing xml layout instructions

"Inside the layout folder we need to create a new file named default.xml, the basic structure for this file is:
```xml
<?xml version="1.0"?>" end of exemplar


and failing to properly close body tag in "<body>
     <move element="nosto.page.home1" destination="header.container" as="new_alias"/>
</body" end of exemplar

**Comment by olsi-qose** [comment]
Thank you @eCommerceGorilla ! 
It should be fixed now!
